### ISSUE TITLE
Bouton 'finanances' --> ouvrir feuille 'caisse'

### ISSUE THREAD

**Issue by SofijnConsultingGroup** [StijnGoossens/Aprovba#9]
Caisse lijkt mij het meestgebruikte blad voor de financien, dus dat lijkt mij ook het default blad te moeten zijn

**Comment by StijnGoossens** [comment]
Huidige functionaliteit stuurt de gebruiker naar de eerste tab in de lijst in het tabblad "VBA". Dit lijkt mij het meest robust. Moesten de namen van de tabbladen in de toekomst wijzigen dan is het het beste om ze niet hard te coderen.
